// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhZPeMTN5BZknFaUFDHJgDtzZapO0WE0M',
    appId: '1:488548195397:web:44c253635276e25da6972c',
    messagingSenderId: '488548195397',
    projectId: 'toplulug',
    authDomain: 'toplulug.firebaseapp.com',
    storageBucket: 'toplulug.appspot.com',
    measurementId: 'G-V4VDXZYN8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-EaucQHV16-FDU0OkESwy4hDuUlkUvWw',
    appId: '1:488548195397:android:7ccecba501b92b1ca6972c',
    messagingSenderId: '488548195397',
    projectId: 'toplulug',
    storageBucket: 'toplulug.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3rWnR3wxjcqRAJI4b8n5AXFL0vmcT0KM',
    appId: '1:488548195397:ios:487f5c009a740099a6972c',
    messagingSenderId: '488548195397',
    projectId: 'toplulug',
    storageBucket: 'toplulug.appspot.com',
    iosBundleId: 'com.example.toplulugum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3rWnR3wxjcqRAJI4b8n5AXFL0vmcT0KM',
    appId: '1:488548195397:ios:471576ed83d6872ea6972c',
    messagingSenderId: '488548195397',
    projectId: 'toplulug',
    storageBucket: 'toplulug.appspot.com',
    iosBundleId: 'com.example.toplulugum.RunnerTests',
  );
}
